[package]
name = "unipac"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
directories = "6.0.0"
indicatif = "0.17.11"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
