[general]
plugins = [
  "$CARGO_MANIFEST_DIR/examples/bash/plugin.sh",
  "$CARGO_MANIFEST_DIR/plugins/pacman/pacman.sh",
  "$CARGO_MANIFEST_DIR/plugins/nix-profile/nix-profile.sh",
  # "$CARGO_MANIFEST_DIR/examples/test_error/plugin.sh",
  # "$CARGO_MANIFEST_DIR/examples/test_error/with_name.sh",
]
