#!/usr/bin/env bash

case "$1" in
  unipac_get_id) echo "Response $ID"; exit 0;;
  unipac_get_name) echo "Response $NAME"; exit 0;;
  unipac_get_color) echo "Response $COLOR"; exit 0;;
esac

if [ -n "$DEPENDENCIES" ]; then
  for dependency in "${DEPENDENCIES[@]}"; do
    if ! command -v "$dependency" >/dev/null; then
      echo "Error $dependency not found"
      exit 1
    fi
  done
fi

$@ 2>/dev/null
code=$?
if [ "$code" -eq 127 ]; then
  echo "Error Command $1 not found"
elif [ "$code" -ne 0 ]; then
  echo "Error Unknown error while executing $1"
fi
